CREATE DATABASE Library
GO

USE Library
GO

CREATE TABLE Publishers
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
	[Location] NVARCHAR(100) NOT NULL
)

CREATE TABLE Books
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Title NVARCHAR(200) NOT NULL,
	PublicationYear INT NOT NULL CHECK(PublicationYear BETWEEN 1500 AND 2026),
	ISBN CHAR(13) NOT NULL UNIQUE,
	CopiesAvailable INT NOT NULL CHECK(CopiesAvailable >= 0),
	PublisherID INT NOT NULL REFERENCES Publishers(ID)
)

CREATE TABLE Authors
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	BirthYear INT NOT NULL CHECK(BirthYear > 1500)
)

CREATE TABLE Readers
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	Phone CHAR(10) NOT NULL UNIQUE,
	RegistrationDate DATE NOT NULL DEFAULT CURRENT_DATE
)

CREATE TABLE Loans
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	BookID INT NOT NULL REFERENCES Books(ID),
	ReaderID INT NOT NULL REFERENCES Readers(ID),
	LoanDate DATE NOT NULL,
	ReturnDate DATE
)

CREATE TABLE Genres
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL UNIQUE,
)

CREATE TABLE ReaderCards
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	ReaderID INT NOT NULL REFERENCES Readers(ID),
	IssueDate DATE NOT NULL,
	ExpiryDate DATE NOT NULL
)

CREATE TABLE BookSeries
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(200) NOT NULL,
	BooksInSeries INT NOT NULL
)

CREATE TABLE Reviews
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	BookID INT NOT NULL REFERENCES Books(ID),
	ReviewText NVARCHAR(MAX) NOT NULL,
	Rating INT NOT NULL CHECK(Rating BETWEEN 1 AND 5)
)

CREATE TABLE Shops
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	[Name] NVARCHAR(100) NOT NULL,
	[Address] NVARCHAR(200) NOT NULL
)

CREATE TABLE ShopInventory
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	ShopID INT NOT NULL REFERENCES Shops(ID),
	BookID INT NOT NULL REFERENCES Books(ID),
	Quantity INT NOT NULL CHECK(Quantity >= 0)
)

CREATE TABLE AuthorAwards
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	AuthorID INT NOT NULL REFERENCES Authors(ID),
	AwardName NVARCHAR(200) NOT NULL,
	YearAwarded INT NOT NULL
)

CREATE TABLE Languages
(
	ID INT IDENTITY NOT NULL PRIMARY KEY,
	Language NVARCHAR(100) NOT NULL
)